
#pragma once

#include "Lexem.hpp"
#include "Vocabulary.hpp"

#include <fstream>
#include <regex>

/**
 * @class Lexer
 * @brief Performs lexical analysis of the source code.
 */
class Lexer {
public:
    /**
     * @brief Constructs the lexer with a given vocabulary.
     * @param vocabulary Reference to a vocabulary object.
     */
    Lexer(Vocabulary& vocabulary);

    /**
     * @brief Performs lexical analysis of a file.
     * @param filepath Path to the source code file.
     */
    void fileCodeAnalysis(const std::string& filepath);

    /**
     * @brief Tokenizes a single line of code.
     * @param str Input string line.
     * @param numberOfRow Line number.
     */
    void tokenizeStringLine(const std::string& str, int numberOfRow);

    /**
     * @return List of tokens generated by the lexer.
     */
    std::vector<Lexem>& getTokens();

private:
    std::vector<Lexem> m_tokens;

    Vocabulary& m_vocabulary;
};
